### PR TITLE
[JENKINS-57229] Bogus serialization of FilePath in CloverHtmlBuildAction

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-57229](https://issues.jenkins-ci.org/browse/JENKINS-57229)

https://github.com/jenkinsci/jenkins/pull/3980 highlighted that this plugin was saving a `FilePath` via XStream, which is not supported. In fact the `FilePath` always had a null `Channel`, since it was nothing more than a representation of a `File` on the Jenkins master.

Untested, YMMV.

### CODE REVIEW

**Comment by jglick** [comment]
> I do not think it is a good idea to pull reports from remote locations for display.

It does not. The reports were always on master. The use of `FilePath` just made no sense in this context. I think it was only done because the calling code used various convenience methods in `FilePath`, and so it called the `<init>(File)` constructor.

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/pull/4011 is the amelioration.

**Comment by jglick** [comment]
There may be `OldDataMonitor` warnings but so what? Leaving the field there would be much worse.

**Comment by marcoreni** [comment]
Any updates on this?

**Comment by marek-parfianowicz** [comment]
As per http://openclover.org/blog (the 'OpenClover road map' article) we don't have Jenkins plugins development in the short term plans (we focus on other topics). So I can't promise this soon, sorry :-( Unless someone volunteers to throughly test the solution to confirm it indeed works.

**Review by marek-parfianowicz — APPROVED** [review]

**Pull request merged**
