### PR TITLE
Can't open previous builds (older than 60mins) clover coverage reports

### PR DESCRIPTION
**Pull request by tangkun75**
Can't open previous builds (older than 60 minutes of expireAfterAccess) clover coverage reports.

### CODE REVIEW

**Comment by mparfianowicz** [comment]
Hi! Thanks for your pull request! May I ask you to write a unit test for your change before I merge it, please?

**Comment by tangkun75** [comment]
Sure!

**Comment by tangkun75** [comment]
Hi Parfianowicz,
    I've added unit tests for CloverBuildAction.

**Comment by mparfianowicz** [comment]
Thanks a lot for writing this unit test, it looks really fine. Please make these minor adjustments and I'll merge it. 

Is it urgent for you to get a new release of this plugin (i.e. the official one, I presume that you use your local version already)? I'm asking because I would prefer to wait and collect some more pull requests before building new version.

**Comment by tangkun75** [comment]
One questions: the purpose of unit test is to verify that the reports could be generated again after 60 minutes (expiredAfterAccess).
hudson.plugins.clover.CloverBuildAction#reports is private data field and hard-coded with 60 minutes for expire duration. To simulate the expiredAfterAccess, I want to get this private filed (reports) and call its invalidateAll() for expire. Do you have some good way to handle this?

**Comment by mparfianowicz** [comment]
What about adding a method in CloverBuildAction, such as:

`
static void invalidateReportCache() {
  reports.invalidateAll();
}
`

**Comment by mparfianowicz** [comment]
Awesome work! Thanks a lot for your contribution!

**Pull request merged**
